# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellidos', models.CharField(max_length=40)),
                ('Identificacion', models.CharField(max_length=10, unique=True)),
                ('Ciudad', models.CharField(blank=True, max_length=60)),
                ('Direccion', models.CharField(blank=True, max_length=200)),
                ('Telefono', models.CharField(blank=True, max_length=10)),
                ('Sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=12)),
                ('E-mail', models.EmailField(blank=True, max_length=254, unique=True)),
                ('Foto', models.ImageField(upload_to='')),
                ('Tipo', models.CharField(choices=[('Super', 'Super'), ('Admin', 'Admin')], max_length=12)),
                ('Tipo de indentificacion', models.CharField(choices=[('cc', 'cc'), ('ti', 'ti'), ('otro', 'otro')], max_length=12)),
                ('Contraseña', models.CharField(max_length=16)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=40)),
                ('Num_id', models.CharField(max_length=10, unique=True)),
                ('Logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellidos', models.CharField(max_length=40)),
                ('Identificacion', models.CharField(max_length=10, unique=True)),
                ('Ciudad', models.CharField(blank=True, max_length=60)),
                ('Direccion', models.CharField(blank=True, max_length=200)),
                ('Telefono', models.CharField(blank=True, max_length=10)),
                ('Sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=12)),
                ('E-mail', models.EmailField(blank=True, max_length=254, unique=True)),
                ('Foto', models.ImageField(upload_to='')),
                ('Estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], max_length=12)),
                ('Fecha de ingreso', models.DateField(auto_now_add=True)),
                ('Registro civil', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
