# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='Ape',
            new_name='Apellidos',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Ciu',
            new_name='Ciudad',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Pass',
            new_name='Contraseña',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Dir',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Email',
            new_name='E-mail',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Num_id',
            new_name='Identificacion',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Nom',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Sex',
            new_name='Sexo',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Tel',
            new_name='Telefono',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Tip_usu',
            new_name='Tipo',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='Tip_id',
            new_name='Tipo de indentificacion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Apellidos',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Email',
            new_name='E-mail',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Fecha_ingreso',
            new_name='Fecha de ingreso',
        ),
    ]
